---
title: "R Notebook"
output: html_notebook
---

## Packages

* [authentification to google](https://cran.r-project.org/web/packages/googleAuthR/vignettes/google-authentication-types.html)


```{r}
pacman::p_load(dplyr, ggplot2, googlesheets, openxlsx)
```

Prepare the OAuth token and set up the target sheet.

* [Example App](https://github.com/jennybc/googlesheets/blob/master/inst/shiny-examples/10_read-write-private-sheet/global.R)
* [Solution](https://stackoverflow.com/questions/32537882/adding-rows-to-a-google-sheet-using-the-r-package-googlesheets
)

## Auth

```{r}
shiny_token <- gs_auth()
#saveRDS(shiny_token, "shiny_app_lol_token.rds")
```

Into the App...

```{r, eval = F}
# googlesheets::gs_auth(token = "shiny_app_lol_token.rds")
# sheet_key <- "1qIPAnsvFh23IZJl-5tfYPc1SnYrbApJ82sXfA4acuaw"
# ss <- googlesheets::gs_key(sheet_key)
```



## Upload


If you have a big dataframe use `gs_upload_big`. Speed up big data uploads by csv upload...

```{r}
gs_upload_big <- function(tbl, data){
  # speed up big data uploads by csv upload
  file_name <- paste0(tbl, ".xlsx")
  openxlsx::write.xlsx(data, file = file_name)

  googlesheets::gs_upload(
    file = file_name, 
    sheet_title = tbl
  )
  file.remove(file_name)
}

gs_upload_big("mtcars1", mtcars)
```

If you only want to initialize a data sheat with some entries use `gs_upload`

```{r}
gs_upload <- function(tbl, data){
  out <- gs_new(
    tbl, 
    input = data, 
    trim = T
  )
  return(out)
}
gs_upload("mtcars2", mtcars)
```

standard functions

```{r}
id <- gs_title("mtcars")
sheet_key <- id$sheet_key 
#id %>% gs_browse()
mtcars <- id %>% gs_read()
```


```{r}
mtcars <- gs_title("mtcars") %>% 
  gs_read()

gs_append_row <- function(tbl, row){
  tbl %>% gs_add_row(input = row)
}
gs_append_row(id, mtcars[1,])


gs_append_rows <- function(tbl, data){
  mtcars %>% 
    split(1:nrow(.)) %>% 
    purrr::walk(~gs_append_row(tbl, .x))
}

gs_append_rows(id, mtcars[1:5,])
#id <- gs_title("no_label")
#id %>% gs_browse()
#no_label <- gs_read(id)
```




